% You need to put t-sne .mat files generated by WADA.py under the same path with this matlab
% script first


% color t-sne embeddings accroding to domain 
tsne_domain = load(".//TSNE_domain_2D.mat")
x = tsne_domain.x
y = tsne_domain.y
label = tsne_domain.label
domain_fig = scatter(x,y,20,label, "filled")
axis off
saveas(domain_fig, "TSNE_domain_2D", "png")

% color t-sne embeddings accroding to label
tsne_label = load(".//TSNE_label_2D.mat")
x = tsne_label.x
y = tsne_label.y
label = tsne_label.label
label_fig = scatter(x,y,20,label, "filled")
axis off
saveas(label_fig, "TSNE_label_2D", "png")